databases:
  - name: dicestock-db
    plan: free
    databaseName: dicestock

services:
  - type: web
    name: dicestock
    runtime: node
    plan: free
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DEV_PIN
        value: "1337"
      - key: DATABASE_URL
        fromDatabase:
          name: dicestock-db
          property: connectionString
